
version: '2'

networks:
  bymn:
    external:
      name: my-net

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=DEBUG
        - FABRIC_LOGGING_SPEC=INFO
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.example.com
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyp-net
    extra_hosts:
        - "peer1.org1.example.com:178.128.204.29"
    ports:
        - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      bymn:
        aliases:
            - ca.example.com
  
  orderer.example.com:
    image: hyperledger/fabric-orderer
    environment:
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_LISTENPORT=7050
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
        - ORDERER_GENERAL_TLS_ENABLED=false
    volumes:
        - ./network-config/:/var/hyperledger/configs
        - ./crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
        - ./channel-artifacts/genesis.block:/var/hyperledger/configs/orderer.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    extra_hosts:
        - "peer1.org1.example.com:178.128.204.29"
    command: orderer
    container_name: orderer.example.com
    networks:
      bymn:
        aliases:
            - orderer.example.com
    ports:
      - '7050'
  
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - bymn

  peer0.org1.example.com:
    image: hyperledger/fabric-peer
    environment:
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=DEBUG
        - CORE_PEER_NETWORKID=peer0.org1.example.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_ID=peer0.org1.example.com
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.example.com:7050
        - CORE_PEER_GOSSIP_IGNORESECURITY=true
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
        - CORE_PEER_TLS_ENABLED=false
        - CORE_PEER_GOSSIP_USELEADERELECTION=false
        - CORE_PEER_GOSSIP_ORGLEADER=true
        - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    extra_hosts:
        - "peer1.org1.example.com:178.128.204.29"
    container_name: peer0.org1.example.com
    command: peer node start
    networks:
      bymn:
        aliases:
          - peer0.org1.example.com
    depends_on:
      - couchdb0
    ports:
      - 8051:7051
      - 8053:7053