
version: '3'

networks:
  bymn:
    external:
      name: my-net

services:
  couchdb1:
      container_name: couchdb1
      image: hyperledger/fabric-couchdb
      # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
      # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
      environment:
        - COUCHDB_USER=
        - COUCHDB_PASSWORD=
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
      # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
      # for example map it to utilize Fauxton User Interface in dev environments.
      ports:
        - "6984:5984"
      networks:
        - bymn

  peer1.org1.example.com:
    image: hyperledger/fabric-peer
    environment:
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=DEBUG
        - CORE_PEER_NETWORKID=peer1.org1.example.com
        - CORE_NEXT=true
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_ID=peer1.org1.example.com
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.example.com:7050
        - CORE_PEER_GOSSIP_IGNORESECURITY=true
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
        - CORE_PEER_TLS_ENABLED=false
        - CORE_PEER_GOSSIP_USELEADERELECTION=false
        - CORE_PEER_GOSSIP_ORGLEADER=true
        - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    extra_hosts:
        - "orderer.example.com:46.101.192.236"
        - "peer0.org1.example.com:46.101.192.236"
    external_links:
        - "orderer.example.com:orderer.example.com"
        - "peer0.org1.example.com:peer0.org1.example.com"
    container_name: peer1.org1.example.com
    command: peer node start
    networks:
      bymn:
        aliases:
          - peer1.org1.example.com
    depends_on:
      - couchdb1
    ports:
      - 9051:7051
      - 9053:7053