version: '3'

networks:
  bymn:
    external:
      name: my-net

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_NETWORKID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh'
    extra_hosts:
        - "orderer.example.com:46.101.192.236"
        - "peer0.org1.example.com:46.101.192.236"
        - "peer1.org1.example.com:178.128.204.29"
    external_links:
        - "orderer.example.com:orderer.example.com"
        - "peer0.org1.example.com:peer0.org1.example.com"
        - "peer1.org1.example.com:peer1.org1.example.com"
    ports:
      - "12051:7051"
      - "12053:7053"
    networks:
      bymn:
        aliases:
          - cli